import type { Metadata } from "next";
import { figtree } from './fonts';
import "./globals.css";
import Navbar from "@/components/header/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={figtree.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
